import type { ChampionTree } from "./types/placemark-types";

export const trees: ChampionTree[] = [
  {
    species: "Douglas fir",
    location: "Powerscourt Gardens, Enniskerry, Co Wicklow",
    latitude: 53.1842,
    longitude: -6.1867,
    height: 57.5,
    girth: 4.86,
    province: "Leinster",
    images: [],
  },
  {
    species: "Sitka spruce",
    location: "Curraghmore, Portlaw, Co Waterford",
    latitude: 52.2083,
    longitude: -7.2923,
    height: 55.0,
    girth: 6.70,
    province: "Munster",
    images: [],
  },
  {
    species: "Sitka spruce",
    location: "Powerscourt Gardens, Enniskerry, Co Wicklow",
    latitude: 53.1842,
    longitude: -6.1867,
    height: 55.0,
    girth: 6.40,
    province: "Leinster",
    images: [],
  },
  {
    species: "Sitka spruce",
    location: "Caledon Estate, Caledon, Co Tyrone",
    latitude: 54.3672,
    longitude: -7.2702,
    height: 55.0,
    girth: 5.77,
    province: "Ulster",
    images: [],
  },
  {
    species: "Sitka spruce",
    location: "Shelton Abbey, Arklow, Co Wicklow",
    latitude: 52.8012,
    longitude: -6.1585,
    height: 54.5,
    girth: 6.61,
    province: "Leinster",
    images: [],
  },
  {
    species: "Douglas fir",
    location: "Avondale Forest Park, Rathdrum, Co Wicklow",
    latitude: 52.9375,
    longitude: -6.2322,
    height: 54.0,
    girth: 3.44,
    province: "Leinster",
    images: [],
  },
  {
    species: "Wellingtonia",
    location: "Luttrelstown Castle, Castleknock, Co Dublin",
    latitude: 53.3846,
    longitude: -6.4012,
    height: 54.0,
    girth: 6.55,
    province: "Leinster",
    images: [],
  },
  {
    species: "Sitka spruce",
    location: "Tempo Manor, Tempo, Co Fermanagh",
    latitude: 54.3217,
    longitude: -7.5802,
    height: 54.0,
    girth: 5.20,
    province: "Ulster",
    images: [],
  },
  {
    species: "Wellingtonia",
    location: "Caledon Estate, Caledon, Co Tyrone",
    latitude: 54.3672,
    longitude: -7.2702,
    height: 53.5,
    girth: 6.35,
    province: "Ulster",
    images: [],
  },
  {
    species: "Douglas fir",
    location: "Avondale Forest Park, Rathdrum, Co Wicklow",
    latitude: 52.9375,
    longitude: -6.2322,
    height: 53.5,
    girth: 3.34,
    province: "Leinster",
    images: [],
  }
];
